#!/bin/bash

RESET="\033[0;m"
BOLD="\033[1;m"

A="\033[32m"
B="\033[32m"

os=$(./utils/get_os | awk 'NR==1 {print $2 " " $3 " " $4}')
os_ver=$(./utils/get_os | awk 'NR==2 {print $2 " " $3 " " $4}')

pkgs=$(./utils/get_packages)
#pkg_names=$(./utils/get_packages --names)

if [ $DE -z ]
then
    de=$(./utils/get_desktop)
else
    de="${DE}"
fi

# tree structure copied from tfetch
echo -e """.
${RESET}├─ ${BOLD}${A}distro${RESET}
${RESET}│  ├─ ${B}${os}${RESET}
${RESET}│  └─ ${B}${os_ver}${RESET}
${RESET}├─ ${BOLD}${A}packages${RESET}
${RESET}│  └─ ${B}all${RESET}
${RESET}│     └─ ${B}${pkgs}${RESET}
${RESET}├─ ${BOLD}${A}env${RESET}
${RESET}│  ├─ ${BOLD}${B}de${RESET}
${RESET}│  │  └─ ${B}${de}${RESET}
${RESET}│  └─ ${BOLD}${B}wm${RESET}
${RESET}│     └─ ${B}{wm}${RESET}
${RESET}└─ ${BOLD}${A}shell${RESET}
${RESET}   └─ ${B}${SHELL##*/}${RESET}
"""
