#!/bin/bash

RESET="\033[0;m"
BOLD="\033[1;m"
BOLD=""

A="\033[32m"
B="\033[32m"

A="\033[38;5;200m"
B="\033[38;5;206m"

A="\033[38;5;92m"
B="\033[38;5;89m"

A="\033[38;5;100m"
B="\033[38;5;243m"


A="\033[38;5;160m"
B="\033[38;5;33m"

A="\033[30m"
B="\033[35m"

os=$(./utils/get_os | awk 'NR==1 {print $2 " " $3 " " $4}')
os_ver=$(./utils/get_os | awk 'NR==2 {print $2 " " $3 " " $4}')

pkgs=$(./utils/get_packages)
#pkg_names=$(./utils/get_packages --names)

if [ -z "$DE"]
then
    de=$(./utils/get_desktop)
else
    de="${DE}"
fi

if [ -z "$WM" ]
then
    wm=$(./utils/get_wm)
else
    wm="${WM}"
fi

# tree structure copied from tfetch
echo -e """.
${RESET}├─ ${BOLD}${A}distro${RESET}
${RESET}│  ├─ ${B}${os}${RESET}
${RESET}│  └─ ${B}${os_ver}${RESET}
${RESET}├─ ${BOLD}${A}packages${RESET}
${RESET}│  └─ ${B}all${RESET}
${RESET}│     └─ ${B}${pkgs}${RESET}
${RESET}├─ ${BOLD}${A}env${RESET}
${RESET}│  ├─ ${BOLD}${B}de${RESET}
${RESET}│  │  └─ ${B}${de}${RESET}
${RESET}│  └─ ${BOLD}${B}wm${RESET}
${RESET}│     └─ ${B}${wm}${RESET}
${RESET}└─ ${BOLD}${A}shell${RESET}
${RESET}   └─ ${B}${SHELL##*/}${RESET}
"""
