#!/bin/bash

mac_os_managers=("brew" "port")
used_managers=()

for manager in "${mac_os_managers[@]}"
do
    command -v "${manager}" &> /dev/null
    if [ $? -eq 0 ]
    then
	used_managers+=("${manager}")
    fi
done

for manager in "${used_managers[@]}"
do
     echo "$manager"
done
