#!/bin/bash

# check homebrew

if [ $(command -v brew &> /dev/null)  -n ]
then
    brew_pkgs=$(($(brew list | wc -l | xargs) - 4))
    #echo $brew_pkgs
else
    brew_pkgs=0
fi

# check mac ports
if [ $(command -v port &> /dev/null) -n  ]
then
    port_pkgs=$(($(port installed 2> /dev/null | wc -l | xargs)))
    #echo $port_pkgs
else
    port_pkgs=0
fi

all_pkgs=$(($brew_pkgs + $port_pkgs))
echo "${all_pkgs}"
