#!/usr/bin/env python3

from platform import system
from platform import release
from os import environ

# helpful info from neofetch's get_de function on line 1771
# https://github.com/dylanaraps/neofetch/blob/master/neofetch

# more info
# https://superuser.com/questions/1074068/what-is-the-difference-between-desktop-session-xdg-session-desktop-and-xdg-cur


def get_de():
    """returns the desktop environment or an error"""
    os = system()

    if os == "Windows":
        if release() == 10:
            return "fluent"
        if release() == 8:
            return "metro"
        # else
        return "aero"
    elif os == "Darwin":  # refers to mac
        return "aqua"
    elif os == "Linux":
        # returns a string with list items seperated with colons
        try:
            desktops_env = environ["XDG_SESSION_DESKTOP"]
        except KeyError:
            # this means the variable isn't setattr
            return "XDG_SESSION_DESKTOP env not found"
        else:
            recognised_desktops = [
                "gnome", "plasma",
                "mate", "xfce",
                "cinnamon", "deepin",
                "budgie", "lxqt",
                "lumina", "trinity",
                "unity", "lxde",
                "ede", "cde", 
                "pantheon", "paperde", 
                "cutefish", "ukui"
            ]
            for desktop in recognised_desktops:
                if desktop in desktops_env.lower():
                    return desktop
            # if the function hasn't returned already
            return "de not recognised"


if __name__ == "__main__":
    print(get_de())
